package com.paperflow.admin.dto;

public record CausalClaimDto(
        long recordId,
        String workId,
        String title,
        Integer publicationYear,
        String sourceId,
        String sourceName,
        String topicName,
        String subfieldName,
        Long claimId,
        String claim,
        String cause,
        String effect,
        String causeStandard,
        String effectStandard,
        String signOfImpact,
        String signCategory,
        String typeOfRelationship,
        String causalInferenceMethod,
        String evidenceMethodOtherDescription,
        Boolean isMainContribution,
        String levelOfTentativeness,
        String sourcesOfExogenousVariation,
        String statisticalSignificance,
        Double causeScore,
        Double effectScore,
        String evidence) {}
