package com.paperflow.admin.dto;

public enum ErrorCode {
    UNAUTHORIZED,
    FORBIDDEN,
    ADMIN_USER_NOT_FOUND,
    ADMIN_USER_CONFLICT,
    VALIDATION_ERROR,
    SOURCE_NOT_FOUND,
    OPENALEX_JOURNAL_IMPORT_NOT_FOUND,
    OPENALEX_JOURNAL_IMPORT_CONFLICT,
    WORK_NOT_FOUND,
    ORIGINAL_FILE_NOT_FOUND,
    PAPER_NOT_FOUND,
    PAPER_ALREADY_EXISTS,
    PAPER_IN_TRASH,
    PAPER_VERSION_CONFLICT,
    PAPER_MATCHED_FIELDS_LOCKED,
    PAPER_STORAGE_CONFLICT,
    INVALID_PAPER_FILE,
    PAPER_FILE_TOO_LARGE,
    PURGE_CONFIRMATION_REQUIRED,
    INTERNAL_ERROR
}
