package com.paperflow.admin.controller;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import jakarta.servlet.http.Cookie;
import org.springframework.http.MediaType;
import org.springframework.mock.web.MockHttpSession;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

abstract class AdminAuthTestSupport {
    static final String ADMIN_PASSWORD_HASH = "$2a$10$nL.EwMm9Y5qmsn1vf.tHBuQfH3uEWcc6vqTc.YiTue3qdQCkh02Ke";
    static final String USER_PASSWORD_HASH = "$2a$10$d9LJngHjSIGiSGyN2s.N8e.G08M/QwWnqaklBYVLNiJl53wMzlubK";
    static final String OLD_PASSWORD_HASH = "$2a$10$bjCtpqKONEq5z0ftG2BTweAMZRw7qLG15fCwhESZSs85tNSmRzQVu";

    static final String DROP_ADMIN_USER_TABLE = "DROP TABLE IF EXISTS admin_user";
    static final String CREATE_ADMIN_USER_TABLE =
            "CREATE TABLE admin_user ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "username VARCHAR(50) NOT NULL CHECK (username ~ '^[A-Za-z0-9_.-]{3,50}$'),"
                    + "username_normalized VARCHAR(50) NOT NULL UNIQUE,"
                    + "password_hash VARCHAR(100) NOT NULL,"
                    + "display_name VARCHAR(100),"
                    + "role VARCHAR(20) NOT NULL CHECK (role IN ('SUPER_ADMIN', 'ADMIN', 'USER')),"
                    + "enabled BOOLEAN NOT NULL DEFAULT TRUE,"
                    + "last_login_at TIMESTAMP WITH TIME ZONE,"
                    + "created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),"
                    + "updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()"
                    + ")";

    LoginSession login(MockMvc mockMvc, String username, String password) throws Exception {
        Csrf csrf = csrf(mockMvc);
        MvcResult result = mockMvc.perform(post("/api/auth/login")
                        .cookie(csrf.cookie())
                        .header("X-XSRF-TOKEN", csrf.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                        {"username":"%s","password":"%s"}
                        """
                                .formatted(username, password)))
                .andExpect(status().isOk())
                .andReturn();
        return new LoginSession((MockHttpSession) result.getRequest().getSession(false), csrf.cookie());
    }

    void assertLoginFails(MockMvc mockMvc, String username, String password) throws Exception {
        Csrf csrf = csrf(mockMvc);

        mockMvc.perform(post("/api/auth/login")
                        .cookie(csrf.cookie())
                        .header("X-XSRF-TOKEN", csrf.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                        {"username":"%s","password":"%s"}
                        """
                                .formatted(username, password)))
                .andExpect(status().isUnauthorized())
                .andExpect(jsonPath("$.code").value("UNAUTHORIZED"));
    }

    Csrf csrf(MockMvc mockMvc) throws Exception {
        MvcResult result = mockMvc.perform(get("/api/auth/csrf"))
                .andExpect(status().isOk())
                .andReturn();
        Cookie cookie = result.getResponse().getCookie("XSRF-TOKEN");
        return new Csrf(cookie, cookie.getValue());
    }

    record Csrf(Cookie cookie, String token) {}

    record LoginSession(MockHttpSession session, Cookie csrfCookie) {}
}
