"""
初始化数据库结构。

作用：
1. 创建 claim_table
2. 创建 paper_claim_table
3. 创建 stw_label
4. 创建必要的唯一约束和索引

说明：
- 这是“首次建库/重建表结构”脚本，不负责导入数据。
- 如果你已经有表结构，且不想重建，把 RESET_TABLES 改成 False。
"""

from __future__ import annotations

import psycopg
from config import connect_db
# True = 每次执行都重建表结构，适合初始化阶段
RESET_TABLES = True

def setup_schema(cur):
    """
    创建正式表。

    说明：
    - claim_table：因果 claim 去重后的标准表
    - paper_claim_table：论文与 claim 的关联表
    - stw_label：主题词 URL -> 英文标签映射表
    """
    if RESET_TABLES:
        cur.execute(
            """
            DROP TABLE IF EXISTS
                paper_claim_table,
                claim_table,
                stw_label
            CASCADE;
            """
        )

    # -----------------------------------------------------
    # claim_table
    # -----------------------------------------------------
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS claim_table (
            claim_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            cause_standard   VARCHAR(255) NOT NULL,
            effect_standard  VARCHAR(255) NOT NULL,
            claim_hash       VARCHAR(64)  NOT NULL UNIQUE,
            created_at       TIMESTAMP    NOT NULL DEFAULT NOW()
        );
        """
    )

    # -----------------------------------------------------
    # paper_claim_table
    #
    # 你后面确认的业务规则：
    # - 同一 paper_id 下，如果 cause + effect 一样，就认为是重复
    # - 所以唯一约束放在 (paper_id, cause, effect)
    # -----------------------------------------------------
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS paper_claim_table (
            record_id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            paper_id                          VARCHAR(100) NOT NULL,
            claim_id                          BIGINT NOT NULL REFERENCES claim_table (claim_id),
            sign_of_impact                    VARCHAR(50) NOT NULL,
            type_of_relationship              VARCHAR(100) NOT NULL,
            claim                             TEXT NOT NULL,
            cause                             TEXT NOT NULL,
            cause_score                       NUMERIC(4,3) NULL,
            effect                            TEXT NOT NULL,
            effect_score                      NUMERIC(4,3) NULL,
            evidence                          TEXT NOT NULL,
            causal_inference_method           VARCHAR(100) NOT NULL,
            evidence_method_other_description TEXT NULL,
            is_main_contribution              BOOLEAN NOT NULL,
            level_of_tentativeness            VARCHAR(50) NULL,
            sources_of_exogenous_variation    TEXT NULL,
            statistical_significance          VARCHAR(100) NULL,
            created_at                        TIMESTAMP NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_paper_claim_unique
                UNIQUE (paper_id, cause, effect)
        );
        """
    )

    # -----------------------------------------------------
    # 索引：常用检索字段
    # -----------------------------------------------------
    cur.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_claim_table_cause_standard
        ON claim_table (cause_standard);
        """
    )

    cur.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_claim_table_effect_standard
        ON claim_table (effect_standard);
        """
    )

    cur.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_paper_claim_table_paper_id
        ON paper_claim_table (paper_id);
        """
    )

    cur.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_paper_claim_table_claim_id
        ON paper_claim_table (claim_id);
        """
    )

    # -----------------------------------------------------
    # stw_label
    # -----------------------------------------------------
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS stw_label (
            id TEXT PRIMARY KEY,
            label_en TEXT NOT NULL
        );
        """
    )


def main():
    conn = connect_db()
    try:
        with conn.cursor() as cur:
            setup_schema(cur)
        conn.commit()
        print("\n✅ 数据库结构初始化完成")
    except Exception as e:
        conn.rollback()
        print(f"\n❌ 初始化失败: {e}")
        raise
    finally:
        conn.close()


if __name__ == "__main__":
    main()
