package com.paperflow.admin.service;

import jakarta.annotation.PostConstruct;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class AdminSchemaInitializer {
    private final JdbcTemplate jdbcTemplate;

    public AdminSchemaInitializer(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @PostConstruct
    void initialize() {
        jdbcTemplate.execute(
                """
                CREATE TABLE IF NOT EXISTS admin_audit_log (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  actor_id BIGINT,
                  actor_username VARCHAR(50),
                  action VARCHAR(80) NOT NULL,
                  target_type VARCHAR(80) NOT NULL,
                  target_id VARCHAR(255),
                  result VARCHAR(20) NOT NULL,
                  request_id VARCHAR(80),
                  remote_addr VARCHAR(100),
                  user_agent VARCHAR(500),
                  message VARCHAR(1000),
                  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_admin_audit_log_created_at ON admin_audit_log(created_at DESC)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_admin_audit_log_actor ON admin_audit_log(actor_username)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_admin_audit_log_action ON admin_audit_log(action)");
    }
}
